version: 2.1
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: ls
      - run:
          command: |
            cd api_testing
            ls
            sudo pip3 install -r requirements.txt
            sudo pip3 install flask_sqlalchemy
            sudo pip3 install flask_marshmallow
            sudo pip3 install coverage
      - run:
          name: Running tests
          command: |
            cd api_testing
            python3 -m unittest test_api
            coverage run -m unittest test_api
            coverage html app.py
      - store_artifacts:
          path: htmlcov