version: 2.1
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    steps:
      - checkout
      - run: ls
      - run:
          command: |
            sudo pip3 install -r requirements.txt
            sudo pip3 install flask_sqlalchemy
            sudo pip3 install flask_marshmallow
#            pip3 install -e .
#            sudo pip3 install pipenv
#            pipenv install
      - run:
          name: Running tests
          command: |
            python3 -m unittest test_api