version: 2.1
jobs:
  build:
#    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    steps:
      - run:
          command: |
            pip3 install -r requirements.txt
            pip3 install -e .
            sudo pip install pipenv
            pipenv install
      - run:
          name: Running tests
          command: |
            ls
            pipenv run python3 -m unittest test_api