version: 2.1
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    steps:
      - checkout
      - run: ls
      - run:
          command: |
            pip3 install -r requirements.txt
            pip3 install -e .
            sudo pip3 install pipenv
            pipenv install
      - run:
          name: Running tests
          command: |
            ls
            pipenv run python3 -m unittest test_api